// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu2CXmeIvlV6CUbdZGS_weaVmyaNoXcxc',
    appId: '1:251767471033:web:0281a51d770b8860ded468',
    messagingSenderId: '251767471033',
    projectId: 'todo-firebase-app-6661f',
    authDomain: 'todo-firebase-app-6661f.firebaseapp.com',
    storageBucket: 'todo-firebase-app-6661f.appspot.com',
    measurementId: 'G-7YDL5WR3YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfP5e2qIrtn7aMB6U-kLsDv2ptJirWfB4',
    appId: '1:251767471033:android:13046d1e8cfe8f48ded468',
    messagingSenderId: '251767471033',
    projectId: 'todo-firebase-app-6661f',
    storageBucket: 'todo-firebase-app-6661f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBNnG9IuDKadj9ORUZhiCUq0K9DP87boc',
    appId: '1:251767471033:ios:65808ce7a53113c7ded468',
    messagingSenderId: '251767471033',
    projectId: 'todo-firebase-app-6661f',
    storageBucket: 'todo-firebase-app-6661f.appspot.com',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBNnG9IuDKadj9ORUZhiCUq0K9DP87boc',
    appId: '1:251767471033:ios:65808ce7a53113c7ded468',
    messagingSenderId: '251767471033',
    projectId: 'todo-firebase-app-6661f',
    storageBucket: 'todo-firebase-app-6661f.appspot.com',
    iosBundleId: 'com.example.todoFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu2CXmeIvlV6CUbdZGS_weaVmyaNoXcxc',
    appId: '1:251767471033:web:6329d7a9024a1495ded468',
    messagingSenderId: '251767471033',
    projectId: 'todo-firebase-app-6661f',
    authDomain: 'todo-firebase-app-6661f.firebaseapp.com',
    storageBucket: 'todo-firebase-app-6661f.appspot.com',
    measurementId: 'G-QWL5Z3YMGH',
  );
}
